% RUN_ECVT_COMPARISON Run the same vehicle/battery model under three strategies.
initialize_model;
comparison_labels = {'Minimum normalized speed','Minimum absolute current', ...
    'Minimum battery degradation'};
comparison_outputs = cell(1,3);
comparison_logs = cell(1,3);
for strategy = 1:3
    in = Simulink.SimulationInput('EV_Backward_Baseline');
    in = in.setVariable('EV_topology',2).setVariable('ecvt_strategy',strategy);
    out = sim(in);
    comparison_outputs{strategy} = out;
    names = {'motor1_torque','motor2_torque','motor1_sun_speed', ...
        'motor2_carrier_speed','motor1_efficiency','motor2_efficiency', ...
        'motor1_mechanical_power','motor2_mechanical_power', ...
        'motor1_electrical_power','motor2_electrical_power','battery_power', ...
        'battery_current','battery_Crate','ecvt_degradation_rate', ...
        'ecvt_loss_per_Ah','ecvt_objective_J','ecvt_feasible'};
    time = out.logsout.get('battery_current').Values.Time;
    data = zeros(numel(time),numel(names));
    for j = 1:numel(names)
        data(:,j) = out.logsout.get(names{j}).Values.Data;
    end
    comparison_logs{strategy} = array2table([time data], ...
        'VariableNames',[{'time_s'} names]);
    writetable(comparison_logs{strategy},sprintf('EV_eCVT_strategy_%d.csv',strategy));
    fprintf('%s: final SOH %.10f, max |I| %.6f A, feasible %.1f%%\n', ...
        comparison_labels{strategy},out.logsout.get('SOH').Values.Data(end), ...
        max(abs(data(:,12))),100*mean(data(:,17)));
end
% Same delivered requests: the aging optimizer cannot do worse than speed.
assert(all(comparison_logs{3}.ecvt_degradation_rate <= ...
    comparison_logs{1}.ecvt_degradation_rate+1e-18));
assert(max(abs(comparison_logs{2}.battery_current- ...
    comparison_logs{3}.battery_current))<1e-7);
save('EV_eCVT_comparison.mat','comparison_outputs','comparison_labels','comparison_logs');
